const doctors = [
  {
    id: 1,
    name: "Dr. Emily Carter",
    specialty: "Cardiologist",
    email: "emily.carter@example.com",
    phone: "+1-555-234-5678",
    location: "New York, USA",
    experience: 12,
    rating: 4.8,
    available: true,
  },
  {
    id: 2,
    name: "Dr. James Patel",
    specialty: "Dermatologist",
    email: "james.patel@example.com",
    phone: "+1-555-345-6789",
    location: "Los Angeles, USA",
    experience: 8,
    rating: 4.5,
    available: false,
  },
  {
    id: 3,
    name: "Dr. Sophia Lee",
    specialty: "Pediatrician",
    email: "sophia.lee@example.com",
    phone: "+1-555-456-7890",
    location: "Chicago, USA",
    experience: 10,
    rating: 4.7,
    available: true,
  },
  {
    id: 4,
    name: "Dr. Daniel Kim",
    specialty: "Neurologist",
    email: "daniel.kim@example.com",
    phone: "+1-555-567-8901",
    location: "Houston, USA",
    experience: 15,
    rating: 4.9,
    available: true,
  },
  {
    id: 5,
    name: "Dr. Olivia Martin",
    specialty: "Psychiatrist",
    email: "olivia.martin@example.com",
    phone: "+1-555-678-9012",
    location: "San Francisco, USA",
    experience: 9,
    rating: 4.6,
    available: false,
  },
  {
    id: 6,
    name: "Dr. Ethan White",
    specialty: "Orthopedic Surgeon",
    email: "ethan.white@example.com",
    phone: "+1-555-789-0123",
    location: "Boston, USA",
    experience: 14,
    rating: 4.8,
    available: true,
  },
  {
    id: 7,
    name: "Dr. Ava Johnson",
    specialty: "Endocrinologist",
    email: "ava.johnson@example.com",
    phone: "+1-555-890-1234",
    location: "Seattle, USA",
    experience: 11,
    rating: 4.7,
    available: true,
  },
  {
    id: 8,
    name: "Dr. William Anderson",
    specialty: "Ophthalmologist",
    email: "william.anderson@example.com",
    phone: "+1-555-901-2345",
    location: "Denver, USA",
    experience: 13,
    rating: 4.9,
    available: false,
  },
  {
    id: 9,
    name: "Dr. Mia Brown",
    specialty: "Gynecologist",
    email: "mia.brown@example.com",
    phone: "+1-555-012-3456",
    location: "Miami, USA",
    experience: 10,
    rating: 4.5,
    available: true,
  },
  {
    id: 10,
    name: "Dr. Benjamin Davis",
    specialty: "General Practitioner",
    email: "benjamin.davis@example.com",
    phone: "+1-555-123-4567",
    location: "Dallas, USA",
    experience: 7,
    rating: 4.4,
    available: true,
  },
];

export default doctors;
