import { Medicine } from "@/types";

export const medicines: Medicine[] = [
  {
    name: "Paracil",
    strength: "500 mg",
    dosageForm: "Tablet",
    generic: "Paracetamol",
    company: "Square Pharmaceuticals",
    mrp: 2.0,
    discount: 1,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8xNzMzNVwvMTczMzUtU2VyZ2VsLWRwMmR1Ni5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjozMDAsImhlaWdodCI6MzAwLCJmaXQiOiJvdXRzaWRlIn19fQ==",
    description: "Effective for reducing fever and mild to moderate pain.",
    pharmachology: "Inhibits prostaglandin synthesis in the brain.",
    dosageAndAdministration: "1-2 tablets every 4-6 hours as needed.",
    interaction: "May interact with anticoagulants like warfarin.",
    sideEffects: "Nausea, rash, liver damage in high doses.",
    overdose: "Symptoms include nausea, vomiting, and liver failure.",
    precautionsAndWarnings: "Use cautiously in liver disease.",
    contraindications: "Severe hepatic impairment.",
    pregnancy: "Considered safe in pregnancy if used as directed.",
    storageConditions: "Store below 25°C in a dry place.",
    disclaimer: "Consult a doctor before use.",
  },
  {
    name: "Amodis",
    strength: "400 mg",
    dosageForm: "Capsule",
    generic: "Amoxicillin",
    company: "Beximco Pharmaceuticals",
    mrp: 5.0,
    discount: 0.15,
    units: "capsule",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8yNDY4M1wvMjQ2ODMtQW1vZGlzLTQwMC1jb3B5LWx3emZnbC5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjozMDAsImhlaWdodCI6MzAwLCJmaXQiOiJvdXRzaWRlIn19fQ==",
    description: "Used for bacterial infections like bronchitis, UTI.",
    pharmachology: "Broad-spectrum beta-lactam antibiotic.",
    dosageAndAdministration: "500 mg every 8 hours for 7 days.",
    interaction: "May reduce efficacy of oral contraceptives.",
    sideEffects: "Diarrhea, nausea, allergic reactions.",
    overdose: "Severe gastrointestinal upset and kidney issues.",
    precautionsAndWarnings: "Adjust dose in renal impairment.",
    contraindications: "Allergy to penicillins.",
    pregnancy: "Safe if prescribed by a physician.",
    storageConditions: "Store below 30°C in original container.",
    disclaimer: "Do not self-prescribe antibiotics.",
  },
  {
    name: "Ace-D",
    strength: "50 mg + 500 mg",
    dosageForm: "Tablet",
    generic: "Diclofenac + Paracetamol",
    company: "Opsonin Pharma",
    mrp: 3.5,
    discount: 0.05,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8yNzE3MVwvMjcxNzEtQWNlLTMwbWwtY29weS1haW81ZGQuanBlZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzAwLCJoZWlnaHQiOjMwMCwiZml0Ijoib3V0c2lkZSJ9fX0=",
    description: "Relieves inflammation and pain in arthritis.",
    pharmachology: "NSAID and analgesic combination.",
    dosageAndAdministration: "1 tablet 2-3 times daily after meals.",
    interaction: "May increase risk of bleeding with anticoagulants.",
    sideEffects: "Stomach upset, dizziness, heartburn.",
    overdose: "Severe gastrointestinal bleeding, kidney damage.",
    precautionsAndWarnings: "Avoid in severe liver or kidney conditions.",
    contraindications: "Active peptic ulcer, hypersensitivity.",
    pregnancy: "Avoid in the third trimester.",
    storageConditions: "Keep away from direct sunlight.",
    disclaimer: "Use only as directed by a healthcare provider.",
  },
  {
    name: "Napa Extra",
    strength: "65 mg + 500 mg",
    dosageForm: "Tablet",
    generic: "Caffeine + Paracetamol",
    company: "Beximco Pharmaceuticals",
    mrp: 3.0,
    discount: 0.1,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8yNTI3MlwvMjUyNzItTmFwYS1FeHRyYS11dmxyMWYuanBlZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzAwLCJoZWlnaHQiOjMwMCwiZml0Ijoib3V0c2lkZSJ9fX0=",
    description: "Relieves headache and fever.",
    pharmachology: "Caffeine potentiates the effect of paracetamol.",
    dosageAndAdministration: "1-2 tablets every 4-6 hours as needed.",
    interaction: "Avoid with excessive coffee consumption.",
    sideEffects: "Insomnia, restlessness, stomach upset.",
    overdose: "Tachycardia, liver damage, restlessness.",
    precautionsAndWarnings: "Do not exceed 4 g of paracetamol daily.",
    contraindications: "Severe hepatic impairment.",
    pregnancy: "Consult with a doctor before use.",
    storageConditions: "Store at room temperature in a dry place.",
    disclaimer: "Do not exceed the recommended dose.",
  },
  {
    name: "Losartan",
    strength: "50 mg",
    dosageForm: "Tablet",
    generic: "Losartan Potassium",
    company: "Eskayef Pharmaceuticals",
    mrp: 7.0,
    discount: 0.2,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8xNDExNVwvMTQxMTUtT3NhcnRpbC01MC03aG5ocHcuanBlZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzAwLCJoZWlnaHQiOjMwMCwiZml0Ijoib3V0c2lkZSJ9fX0=",
    description: "Used for hypertension and heart failure.",
    pharmachology: "Blocks angiotensin II receptors.",
    dosageAndAdministration: "50 mg once daily.",
    interaction: "May interact with potassium supplements.",
    sideEffects: "Dizziness, fatigue, increased potassium levels.",
    overdose: "Severe hypotension and kidney issues.",
    precautionsAndWarnings: "Monitor renal function periodically.",
    contraindications: "Pregnancy, severe renal impairment.",
    pregnancy: "Contraindicated.",
    storageConditions: "Store below 30°C in original packaging.",
    disclaimer: "Monitor blood pressure regularly.",
  },
  {
    name: "Clavomax",
    strength: "625 mg",
    dosageForm: "Tablet",
    generic: "Amoxicillin + Clavulanic Acid",
    company: "Renata Limited",
    mrp: 12.0,
    discount: 0.1,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8zNTkxN1wvMzU5MTctQ2xhcmltYXgtNTAwLWNvcHktZXowN2huLmpwZWciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjMwMCwiaGVpZ2h0IjozMDAsImZpdCI6Im91dHNpZGUifX19",
    description: "Effective against resistant bacterial infections.",
    pharmachology: "Beta-lactam antibiotic with beta-lactamase inhibitor.",
    dosageAndAdministration: "1 tablet every 12 hours for 7-10 days.",
    interaction: "Avoid with methotrexate.",
    sideEffects: "Diarrhea, nausea, skin rash.",
    overdose: "Gastrointestinal upset, kidney issues.",
    precautionsAndWarnings: "Caution in patients with hepatic dysfunction.",
    contraindications: "Hypersensitivity to penicillins.",
    pregnancy: "Safe under doctor's advice.",
    storageConditions: "Store in a cool, dry place.",
    disclaimer: "Complete the full course of antibiotics.",
  },
  {
    name: "Omep",
    strength: "20 mg",
    dosageForm: "Capsule",
    generic: "Omeprazole",
    company: "Incepta Pharmaceuticals",
    mrp: 3.5,
    discount: 0.05,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8xMzY0NlwvMTM2NDYtb21lcC0yMC1jb3B5LWVkNndheS5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjozMDAsImhlaWdodCI6MzAwLCJmaXQiOiJvdXRzaWRlIn19fQ==",
    description: "Used for gastric ulcers and acid reflux.",
    pharmachology: "Proton pump inhibitor that reduces stomach acid.",
    dosageAndAdministration: "20 mg daily before meals.",
    interaction: "May interact with clopidogrel.",
    sideEffects: "Headache, diarrhea, abdominal pain.",
    overdose: "Nausea, confusion, tachycardia.",
    precautionsAndWarnings: "Long-term use may reduce magnesium levels.",
    contraindications: "Allergy to omeprazole.",
    pregnancy: "Safe if prescribed.",
    storageConditions: "Store below 25°C in a dry place.",
    disclaimer: "Take 30 minutes before meals for best results.",
  },
  {
    name: "Montiva",
    strength: "10 mg",
    dosageForm: "Tablet",
    generic: "Montelukast",
    company: "ACI Limited",
    mrp: 5.5,
    discount: 0.1,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC8xMjA5MVwvMTIwOTEtTW9udGl2YS0xMC1jb3B5LThxdTFzby5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjozMDAsImhlaWdodCI6MzAwLCJmaXQiOiJvdXRzaWRlIn19fQ==",
    description: "Used for asthma and allergic rhinitis.",
    pharmachology: "Leukotriene receptor antagonist.",
    dosageAndAdministration: "10 mg once daily in the evening.",
    interaction: "Avoid with aspirin if sensitive.",
    sideEffects: "Drowsiness, abdominal pain, headache.",
    overdose: "Abdominal pain, hyperactivity, thirst.",
    precautionsAndWarnings: "Not for acute asthma attacks.",
    contraindications: "Hypersensitivity to montelukast.",
    pregnancy: "Safe under doctor's advice.",
    storageConditions: "Store below 30°C.",
    disclaimer: "Do not use for sudden breathing problems.",
  },
  {
    name: "Aspiron",
    strength: "75 mg",
    dosageForm: "Tablet",
    generic: "Aspirin",
    company: "Globe Pharmaceuticals",
    mrp: 2.5,
    discount: 0.1,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC82MjA4XC82MjA4LUVjb3NwcmluLTc1LXFkOGdpeC5qcGVnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjozMDAsImhlaWdodCI6MzAwLCJmaXQiOiJvdXRzaWRlIn19fQ==",
    description: "Used for preventing blood clots.",
    pharmachology: "Irreversibly inhibits platelet aggregation.",
    dosageAndAdministration: "75 mg once daily after meals.",
    interaction: "May increase bleeding with anticoagulants.",
    sideEffects: "Stomach upset, increased bleeding risk.",
    overdose: "Ring in ears, respiratory alkalosis.",
    precautionsAndWarnings: "Caution in patients with bleeding disorders.",
    contraindications: "Active bleeding, hypersensitivity.",
    pregnancy: "Avoid in the third trimester.",
    storageConditions: "Store at room temperature.",
    disclaimer: "Use under medical supervision.",
  },
  {
    name: "Cetral",
    strength: "10 mg",
    dosageForm: "Tablet",
    generic: "Cetirizine",
    company: "ACI Limited",
    mrp: 2.0,
    discount: 0.1,
    units: "strip",
    image:
      "https://cdn2.arogga.com/eyJidWNrZXQiOiJhcm9nZ2EiLCJrZXkiOiJQcm9kdWN0LXBfaW1hZ2VzXC80NjI4XC80NjI4LUNvcmFsY2FsLURYLTAtY29weS02dmpmOGUuanBlZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MzAwLCJoZWlnaHQiOjMwMCwiZml0Ijoib3V0c2lkZSJ9fX0=",
    description: "Relieves allergies and hay fever.",
    pharmachology: "Selective histamine H1 receptor antagonist.",
    dosageAndAdministration: "10 mg once daily.",
    interaction: "Avoid alcohol to prevent excessive drowsiness.",
    sideEffects: "Dry mouth, drowsiness, fatigue.",
    overdose: "Severe drowsiness, agitation, restlessness.",
    precautionsAndWarnings: "Caution in renal impairment.",
    contraindications: "Hypersensitivity to cetirizine.",
    pregnancy: "Safe under medical advice.",
    storageConditions: "Store in a cool, dry place.",
    disclaimer: "Avoid driving if drowsy.",
  },
];
